Vagrant.configure(2) do |config|
  config.vm.define "db-server" do |db|
    db.vm.box = "ubuntu/bionic64"
    db.vm.provider "virtualbox" do |vb|
      vb.memory = "384"  
    end
    db.vm.hostname = "db01"
    db.vm.network "private_network", ip: "192.168.10.200"
      db.vm.network "forwarded_port", guest:3306, host:3306, auto_correct: false
      db.vm.provision "shell", path: "db.sh"
  end
config.vm.provision "shell", inline: <<-SHELL 
    set -o xtrace
	sudo apt-get update
	sudo apt-get -y install debconf-utils 
	sudo apt-get -y install apache2 
	sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password Hallo123'
	sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password Hallo123'
	sudo apt-get -y install php libapache2-mod-php php-curl php-cli php-mysql php-gd mysql-client mysql-server 
	
	sudo mkdir /usr/share/adminer
	sudo wget "http://www.adminer.org/latest.php" -O /usr/share/adminer/latest.php
	sudo ln -s /usr/share/adminer/latest.php /usr/share/adminer/adminer.php
	echo "Alias /adminer.php /usr/share/adminer/adminer.php" | sudo tee /etc/apache2/conf-available/adminer.conf
	sudo a2enconf adminer.conf 
	sudo service apache2 restart 

  sudo ufw allow 80/tcp 
  sudo ufw allow 22/tcp 
  sudo ufw -f enable 
SHELL
end