Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.define "db-server" do |db|
      db.vm.network "public_network", :bridge => "eth0", ip: "192.168.1.100"
      db.vm.network "forwarded_port", guest: 3306, host: 3306
      db.vm.network "forwarded_port", guest: 80, host: 8306
      db.vm.provision "shell", path: “bootstrap.sh"


  #!/usr/bin/env bash

  DBHOST=localhost
  DBNAME=db01
  DBUSER=TestBenutzer
  DBPASSWD=Hallo123
  
  apt-get update
  apt-get install vim curl build-essential python-software-properties git
  
  debconf-set-selections <<< "mysql-server mysql-server/root_password password $Hallo123"
  debconf-set-selections <<< "mysql-server mysql-server/root_password_again password $Hallo123"
  debconf-set-selections <<< "phpmyadmin phpmyadmin/dbconfig-install boolean true"
  debconf-set-selections <<< "phpmyadmin phpmyadmin/app-password-confirm password $Hallo123"
  debconf-set-selections <<< "phpmyadmin phpmyadmin/mysql/admin-pass password $Hallo123"
  debconf-set-selections <<< "phpmyadmin phpmyadmin/mysql/app-pass password $Hallo123"
  debconf-set-selections <<< "phpmyadmin phpmyadmin/reconfigure-webserver multiselect none"
  
  # install mysql and admin interface
  
  apt-get -y install mysql-server phpmyadmin
  
  mysql -uroot -p$DBPASSWD -e "CREATE DATABASE $db01"
  mysql -uroot -p$DBPASSWD -e "grant all privileges on $db01.* to '$TestBenutzer'@'%' identified by '$Hallo123'"
  
  cd /vagrant
  
  # update mysql conf file to allow remote access to the db
  
  sudo sed -i "s/.*bind-address.*/bind-address = 0.0.0.0/" /etc/mysql/mysql.conf.d/mysqld.cnf
  
  sudo service mysql restart
  
  # phpmyadmin installieren
  
  apt-get -y install php apache2 libapache2-mod-php php-curl php-gd php-mysql php-gettext a2enmod rewrite
  
  sed -i "s/AllowOverride None/AllowOverride All/g" /etc/apache2/apache2.conf
  
  rm -rf /var/www/html
  ln -fs /vagrant/public /var/www/html
  
  sed -i "s/error_reporting = .*/error_reporting = E_ALL/" /etc/php/7.0/apache2/php.ini
  sed -i "s/display_errors = .*/display_errors = On/" /etc/php/7.0/apache2/php.ini
  
  service apache2 restart

end   
