version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    restart: always
    networks:
        testing_net:
            ipv4_address: 192.168.60.102

  Web_App_1:
    image: httpd
    container_name: Web_App_1
    volumes:
      - ./http1/index.html:/usr/local/apache2/htdocs/index.html
    expose:
      - "80"
    restart: always
    depends_on:
      - nginx
    networks:
        testing_net:
            ipv4_address: 192.168.60.103

  Web_App_2:
    image: httpd
    container_name: Web_App_2
    volumes:
      - ./http2/index.html:/usr/local/apache2/htdocs/index.html
    expose:
      - "80"
    restart: always
    depends_on:
      - Web_App_1
    networks:
        testing_net:
            ipv4_address: 192.168.60.104

  Web_App_3:
    image: web03
    container_name: Web_App_3
    volumes:
      - ./http3/index.html:/var/www/html/index.html
    expose:
      - "80"
    restart: always
    networks:
        testing_net:
            ipv4_address: 192.168.60.105

networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 192.168.0.0/16